### PR TITLE
Fix string conversion datatypes

### PR DESCRIPTION
**Pull request by lechner**
On architectures where the type (time_t) resolves to (ulong), command line arguments to 'dsn' are not processed correctly. The (void) pointer passed to lib/cli++/main.cc is cast to (unsigned int) instead of (ulong). On 64-bit little endian architectures such as amd64 this is not readily apparent as long as the higher bits were initialized, but it causes grave errors on big-endian architectures such as Debian's powerpc or s390x. This patch processes the timestamps given on the command line correctly.

A similar problem existed in lib/config_readint.cc, which is fixed here as well.

### CODE REVIEW

**Comment by bruceg** [comment]
Thanks, Felix.

**Comment by bruceg** [comment]
Ugh, I didn't notice this before I pushed it out. This broke the build since the changes to lib/cli++/main.cc were incomplete. Obviously this is not the source or patch you are actually using since it cannot compile. Please check it next time.

```
main.cc: In function ‘int calc_width(const cli_option*)’:
main.cc:92:10: error: ‘uinteger’ is not a member of ‘cli_option’
     case cli_option::uinteger:   width += 4; break;
          ^
main.cc:89:12: warning: enumeration value ‘ulong’ not handled in switch [-Wswitch]
     switch (o->type) {
            ^
main.cc: In function ‘void show_option(const cli_option*, int)’:
main.cc:126:10: error: ‘uinteger’ is not a member of ‘cli_option’
     case cli_option::uinteger:   extra = "=UNS"; break;
          ^
main.cc:123:11: warning: enumeration value ‘ulong’ not handled in switch [-Wswitch]
     switch(o->type) {
           ^
main.cc: In member function ‘int cli_option::set(const char*)’:
main.cc:189:34: error: ‘INT_MIN’ was not declared in this scope
       if(*endptr || longresult < INT_MIN || longresult > INT_MAX) {
                                  ^
main.cc:189:58: error: ‘INT_MAX’ was not declared in this scope
       if(*endptr || longresult < INT_MIN || longresult > INT_MAX) {
```

**Comment by lechner** [comment]
It was a longer patch tracking the dereferenced pointer sizes. I did not think you would accept the whole thing and must have forgotten to compile. Sorry, I had been working to find the problem for several days and was working on a Debian porterbox without my Github key. I will update the pull request right now.

**Comment by lechner** [comment]
Sorry, Bruce. I should have checked before submitting. Please see commit b45499e. Thank you!

**Pull request merged**
